[package]
name = "metrics_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9.0"
hyper = { version = "1.5", features = ["client", "server", "http1"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
